In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# read the data
file_path="Resources/FoodAccessResearchAtlas2019.csv"
foodAccessResearchAtlas=pd.read_csv(file_path)
foodAccessResearchAtlas.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [3]:
foodAccessResearchAtlas.columns.tolist()

['CensusTract',
 'State',
 'County',
 'Urban',
 'Pop2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lapophalfshare',
 'lalowihalf',
 'lalowihalfshare',
 'lakidshalf',
 'lakidshalfshare',
 'laseniorshalf',
 'laseniorshalfshare',
 'lawhitehalf',
 'lawhitehalfshare',
 'lablackhalf',
 'lablackhalfshare',
 'laasianhalf',
 'laasianhalfshare',
 'lanhopihalf',
 'lanhopihalfshare',
 'laaianhalf',
 'laaianhalfshare',
 'laomultirhalf',
 'laomultirhalfshare',
 'lahisphalf',
 'lahisphalfshare',
 'lahunvhalf',
 'lahunvhalfshare',
 'lasnaphalf',
 'lasnaphalfshare',
 'lapop1',
 'lapop1share',
 'lalowi1',
 'lalowi1share',
 'lakids1',
 'lakids1share',
 'laseniors1',
 'laseniors1share',
 'lawhite1',
 'lawhite1share',
 'lablack1',
 'lablack1share',
 'laasian1',
 'laasian1share',
 'lanhopi1',
 'lanhopi1share',
 'laaian1',
 'laaian1share',
 'laomultir1',
 'laomultir1share',
 'lahisp1',
 'lahisp1share',
 'lahunv1',
 'lahunv1share',
 'lasnap1',
 'lasnap1share',
 'lapop10',
 'lapop10share',
 'lalowi10',
 'lalowi10share',
 'lakids10',
 'lakids10share',
 'laseniors10',
 'laseniors10share',
 'lawhite10',
 'lawhite10share',
 'lablack10',
 'lablack10share',
 'laasian10',
 'laasian10share',
 'lanhopi10',
 'lanhopi10share',
 'laaian10',
 'laaian10share',
 'laomultir10',
 'laomultir10share',
 'lahisp10',
 'lahisp10share',
 'lahunv10',
 'lahunv10share',
 'lasnap10',
 'lasnap10share',
 'lapop20',
 'lapop20share',
 'lalowi20',
 'lalowi20share',
 'lakids20',
 'lakids20share',
 'laseniors20',
 'laseniors20share',
 'lawhite20',
 'lawhite20share',
 'lablack20',
 'lablack20share',
 'laasian20',
 'laasian20share',
 'lanhopi20',
 'lanhopi20share',
 'laaian20',
 'laaian20share',
 'laomultir20',
 'laomultir20share',
 'lahisp20',
 'lahisp20share',
 'lahunv20',
 'lahunv20share',
 'lasnap20',
 'lasnap20share',
 'TractLOWI',
 'TractKids',
 'TractSeniors',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [4]:
df=pd.DataFrame(foodAccessResearchAtlas)
df.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [5]:
california_foodAccessResearchAtlas=df.loc[df["State"] == "California"]
california_foodAccessResearchAtlas.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,634.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,323.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,493.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,353.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,314.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [6]:
california_foodAccessResearchAtlas.dtypes

CensusTract        int64
State             object
County            object
Urban              int64
Pop2010            int64
                  ...
TractAIAN        float64
TractOMultir     float64
TractHispanic    float64
TractHUNV        float64
TractSNAP        float64
Length: 147, dtype: object

In [7]:
len(california_foodAccessResearchAtlas.index)

8024

In [8]:
california_foodAccessResearchAtlas.tail(10)

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
11565,6115040303,California,Yuba County,1,6555,1969,0,21.0,0.32,0,...,434.0,3782.0,362.0,950.0,42.0,90.0,1329.0,1834.0,76.0,347.0
11566,6115040400,California,Yuba County,1,5538,1625,0,1.0,0.02,1,...,427.0,3136.0,161.0,553.0,39.0,176.0,1473.0,1922.0,300.0,594.0
11567,6115040500,California,Yuba County,1,4111,1220,0,33.0,0.80,1,...,350.0,2529.0,98.0,213.0,10.0,135.0,1126.0,1578.0,127.0,250.0
11568,6115040600,California,Yuba County,1,6130,1846,0,7.0,0.11,1,...,588.0,3892.0,117.0,347.0,14.0,182.0,1578.0,2267.0,52.0,337.0
11569,6115040700,California,Yuba County,0,10879,3320,0,6.0,0.06,0,...,540.0,7103.0,565.0,856.0,103.0,157.0,2095.0,2759.0,86.0,208.0
11570,6115040800,California,Yuba County,0,4233,1492,0,4.0,0.09,0,...,493.0,3289.0,44.0,213.0,5.0,77.0,605.0,713.0,58.0,108.0
11571,6115040901,California,Yuba County,0,2783,968,0,12.0,0.43,0,...,382.0,1997.0,31.0,297.0,2.0,75.0,381.0,476.0,20.0,199.0
11572,6115040902,California,Yuba County,0,1737,385,0,413.0,23.78,0,...,2.0,1262.0,167.0,66.0,9.0,34.0,199.0,247.0,0.0,17.0
11573,6115041000,California,Yuba County,0,7357,2802,0,0.0,0.00,0,...,1247.0,6179.0,57.0,181.0,9.0,156.0,775.0,916.0,43.0,188.0
11574,6115041100,California,Yuba County,0,4941,2105,0,5.0,0.10,0,...,920.0,4287.0,30.0,59.0,13.0,189.0,363.0,314.0,119.0,185.0

In [9]:
clean_df1 = california_foodAccessResearchAtlas.drop([col for col in california_foodAccessResearchAtlas.columns if 'share' in col],axis=1)
clean_df1.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,634.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,323.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,493.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,353.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,314.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [10]:
clean_df2=clean_df1.drop([col for col in clean_df1.columns if "Kids"  in col],axis=1)
clean_df2.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,634.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,323.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,493.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,353.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,314.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [11]:
clean_df2.columns.tolist()

['CensusTract',
 'State',
 'County',
 'Urban',
 'Pop2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lalowihalf',
 'lakidshalf',
 'laseniorshalf',
 'lawhitehalf',
 'lablackhalf',
 'laasianhalf',
 'lanhopihalf',
 'laaianhalf',
 'laomultirhalf',
 'lahisphalf',
 'lahunvhalf',
 'lasnaphalf',
 'lapop1',
 'lalowi1',
 'lakids1',
 'laseniors1',
 'lawhite1',
 'lablack1',
 'laasian1',
 'lanhopi1',
 'laaian1',
 'laomultir1',
 'lahisp1',
 'lahunv1',
 'lasnap1',
 'lapop10',
 'lalowi10',
 'lakids10',
 'laseniors10',
 'lawhite10',
 'lablack10',
 'laasian10',
 'lanhopi10',
 'laaian10',
 'laomultir10',
 'lahisp10',
 'lahunv10',
 'lasnap10',
 'lapop20',
 'lalowi20',
 'lakids20',
 'laseniors20',
 'lawhite20',
 'lablack20',
 'laasian20',
 'lanhopi20',
 'laaian20',
 'laomultir20',
 'lahisp20',
 'lahunv20',
 'lasnap20',
 'TractLOWI',
 'TractSeniors',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [12]:
clean_df3=clean_df2.drop([col for col in clean_df2.columns if "kids" in col],axis=1)
clean_df3.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,634.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,323.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,493.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,353.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,314.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [13]:
clean_df4=clean_df3.drop([col for col in clean_df3.columns if "seniors" in col],axis=1)
clean_df4.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,634.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,323.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,493.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,353.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,314.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [14]:
clean_df5=clean_df4.drop([col for col in clean_df4.columns if "Seniors" in col],axis=1)
clean_df5.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractLOWI,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
3551,6001400100,California,Alameda County,1,2937,1314,0,2.0,0.07,0,...,312.0,2161.0,142.0,456.0,9.0,4.0,165.0,117.0,28.0,0.0
3552,6001400200,California,Alameda County,1,1974,856,0,70.0,3.55,0,...,230.0,1659.0,33.0,147.0,0.0,4.0,131.0,151.0,59.0,0.0
3553,6001400300,California,Alameda County,1,4865,2418,0,40.0,0.82,0,...,526.0,3468.0,518.0,423.0,5.0,17.0,434.0,399.0,423.0,38.0
3554,6001400400,California,Alameda County,1,3703,1779,0,33.0,0.89,0,...,802.0,2628.0,456.0,278.0,6.0,14.0,321.0,332.0,157.0,115.0
3555,6001400500,California,Alameda County,1,3517,1578,0,126.0,3.58,0,...,809.0,1905.0,955.0,209.0,5.0,27.0,416.0,340.0,188.0,51.0

In [15]:
clean_df5.columns.tolist()

['CensusTract',
 'State',
 'County',
 'Urban',
 'Pop2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lalowihalf',
 'lawhitehalf',
 'lablackhalf',
 'laasianhalf',
 'lanhopihalf',
 'laaianhalf',
 'laomultirhalf',
 'lahisphalf',
 'lahunvhalf',
 'lasnaphalf',
 'lapop1',
 'lalowi1',
 'lawhite1',
 'lablack1',
 'laasian1',
 'lanhopi1',
 'laaian1',
 'laomultir1',
 'lahisp1',
 'lahunv1',
 'lasnap1',
 'lapop10',
 'lalowi10',
 'lawhite10',
 'lablack10',
 'laasian10',
 'lanhopi10',
 'laaian10',
 'laomultir10',
 'lahisp10',
 'lahunv10',
 'lasnap10',
 'lapop20',
 'lalowi20',
 'lawhite20',
 'lablack20',
 'laasian20',
 'lanhopi20',
 'laaian20',
 'laomultir20',
 'lahisp20',
 'lahunv20',
 'lasnap20',
 'TractLOWI',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [16]:
FoodAccess_2019_col_list=clean_df5.columns.tolist()
FoodAccess_2019_col_list

['CensusTract',
 'State',
 'County',
 'Urban',
 'Pop2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lalowihalf',
 'lawhitehalf',
 'lablackhalf',
 'laasianhalf',
 'lanhopihalf',
 'laaianhalf',
 'laomultirhalf',
 'lahisphalf',
 'lahunvhalf',
 'lasnaphalf',
 'lapop1',
 'lalowi1',
 'lawhite1',
 'lablack1',
 'laasian1',
 'lanhopi1',
 'laaian1',
 'laomultir1',
 'lahisp1',
 'lahunv1',
 'lasnap1',
 'lapop10',
 'lalowi10',
 'lawhite10',
 'lablack10',
 'laasian10',
 'lanhopi10',
 'laaian10',
 'laomultir10',
 'lahisp10',
 'lahunv10',
 'lasnap10',
 'lapop20',
 'lalowi20',
 'lawhite20',
 'lablack20',
 'laasian20',
 'lanhopi20',
 'laaian20',
 'laomultir20',
 'lahisp20',
 'lahunv20',
 'lasnap20',
 'TractLOWI',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [17]:
col_list2019=pd.DataFrame(FoodAccess_2019_col_list)
col_list2019

                0
0     CensusTract
1           State
2          County
3           Urban
4         Pop2010
..            ...
80      TractAIAN
81   TractOMultir
82  TractHispanic
83      TractHUNV
84      TractSNAP

[85 rows x 1 columns]

In [18]:
clean_df5.isnull().sum().sort_values(ascending = False)

laaian20         7914
lasnap20         7914
lapop20          7914
lalowi20         7914
lawhite20        7914
                 ...
LATracts_half       0
LATracts1           0
LATracts10          0
LATracts20          0
TractSNAP           0
Length: 85, dtype: int64

In [19]:
def missing_values_table(clean_df5):
    mis_val = clean_df5.isnull().sum()
    mis_val_percent = 100 * clean_df5.isnull().sum() / len(clean_df5)
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)
    print ("Your selected dataframe has " + str(clean_df5.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
            " columns that have missing values.")
    return mis_val_table_ren_columns

In [20]:
missing_values_table(clean_df5)

Your selected dataframe has 85 columns.
There are 53 columns that have missing values.

                    Missing Values  % of Total Values
lasnap20                      7914               98.6
laaian20                      7914               98.6
lapop20                       7914               98.6
lawhite20                     7914               98.6
lablack20                     7914               98.6
laasian20                     7914               98.6
lanhopi20                     7914               98.6
lalowi20                      7914               98.6
lahisp20                      7914               98.6
lahunv20                      7914               98.6
laomultir20                   7914               98.6
lahisp10                      7703               96.0
laasian10                     7703               96.0
lapop10                       7703               96.0
lalowi10                      7703               96.0
lawhite10                     7703               96.0
lablack10                     7703               96.0
lasnap10                      7703               96.0
lahunv10                      7703               96.0
laomultir10                   7703               96.0
laaian10                      7703               96.0
lanhopi10                     7703               96.0
LALOWI1_20                    4804               59.9
LAPOP1_20                     4804               59.9
LAPOP1_10                     4623               57.6
LALOWI1_10                    4623               57.6
lahunv1                       4237               52.8
lasnap1                       4237               52.8
laaian1                       4237               52.8
lahisp1                       4237               52.8
lanhopi1                      4237               52.8
laasian1                      4237               52.8
lablack1                      4237               52.8
lawhite1                      4237               52.8
lalowi1                       4237               52.8
lapop1                        4237               52.8
laomultir1                    4237               52.8
LAPOP05_10                    1268               15.8
LALOWI05_10                   1268               15.8
laasianhalf                    881               11.0
lapophalf                      881               11.0
lalowihalf                     881               11.0
lawhitehalf                    881               11.0
lablackhalf                    881               11.0
laomultirhalf                  881               11.0
lanhopihalf                    881               11.0
laaianhalf                     881               11.0
lahisphalf                     881               11.0
lahunvhalf                     881               11.0
lasnaphalf                     881               11.0
MedianFamilyIncome              86                1.1
PCTGQTRS                         1                0.0
NUMGQTRS                         1                0.0

In [21]:
len(clean_df5)

8024

In [22]:
import os  
os.makedirs('Resources', exist_ok=True)  
col_list2019.to_csv('Resources/col_list2019.csv')

In [23]:
clean_df5.to_csv("Resources/FoodAccess2019_clean.csv")